"""Clean train_minutes/ and val_minutes/.

Rules (per user instruction):
  * Valid labels start with t_ / t1_ / t2_  (regex ^t\\d*_).
    Autogenerated labels (absent, occupied, present, empty, left, right,
    radar-missing, ...) are stripped from manifests that parse as JSON.
  * Folders left with NO valid t_* label are deleted.
  * Folders with no manifest.json are deleted.
  * Empty folders (no files, or no radar data at all) are deleted.
  * Folders whose t_* labels disagree on the binary class are deleted
    (ambiguous ground truth).

Deleted folders are moved to _trash/<split>/<name> (recoverable).

Usage:
    python E2/clean_minutes.py --dry-run     # report only
    python E2/clean_minutes.py               # apply
"""
import argparse
import json
import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TRASH = ROOT / "_trash"
VALID = re.compile(r"^t\d*_")
CLASS = {"empty": 0, "present": 1, "sleep": 1}


def _regex_labels(text):
    m = re.search(r'"labels"\s*:\s*\[([^\]]*)\]', text)
    return re.findall(r'"([^"]+)"', m.group(1)) if m else []


def classify(folder):
    """-> (action, reason, valid_labels). action: keep|delete"""
    files = [f for f in folder.rglob("*") if f.is_file()]
    if not files:
        return "delete", "empty folder", []
    has_radar = (folder / "capture.npz").exists() or \
        any(f.name.startswith("radar_") and f.suffix == ".bin"
            for f in files)
    if not has_radar:
        return "delete", "no radar data", []
    mpath = folder / "manifest.json"
    if not mpath.exists():
        return "delete", "no manifest.json", []
    text = mpath.read_text(encoding="utf-8", errors="replace")
    try:
        man = json.loads(text)
        labels = man.get("labels", []) or []
        mode = "json"
    except Exception:
        man, labels, mode = None, _regex_labels(text), "regex"
    valid = [l for l in labels if VALID.match(l)]
    if not valid:
        return "delete", f"no t_* label (labels={labels})", []
    classes = set()
    for l in valid:
        suffix = l.split("_", 1)[1] if "_" in l else ""
        classes.add(CLASS.get(suffix, -1))
    if -1 in classes or len(classes) > 1:
        return "delete", f"ambiguous/unknown t_* labels {valid}", []
    if mode == "json" and set(labels) != set(valid):
        man["labels"] = valid
        mpath.write_text(json.dumps(man, indent=2), encoding="utf-8")
        return "keep", f"stripped auto-labels {sorted(set(labels)-set(valid))}", valid
    return "keep", "ok", valid


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    a = ap.parse_args()
    for split in ("train_minutes", "val_minutes"):
        root = ROOT / split
        kept = deleted = 0
        reasons = {}
        for folder in sorted(root.iterdir()):
            if not folder.is_dir():
                continue
            action, reason, _ = classify(folder)
            if action == "delete":
                deleted += 1
                reasons[reason.split(" (")[0]] = \
                    reasons.get(reason.split(" (")[0], 0) + 1
                if not a.dry_run:
                    dst = TRASH / split / folder.name
                    dst.parent.mkdir(parents=True, exist_ok=True)
                    shutil.move(str(folder), str(dst))
            else:
                kept += 1
                if reason != "ok" and not a.dry_run:
                    pass  # labels stripped in-place by classify()
        print(f"{split}: kept={kept} deleted={deleted} {reasons}")
    if a.dry_run:
        print("(dry run — nothing moved)")


if __name__ == "__main__":
    main()
